name: sona_app
description: SONA - 감정 기반 AI 페르소나 대화 매칭 앱
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.15.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.4.10
  firebase_crashlytics: ^4.0.2
  
  # Authentication
  google_sign_in: ^6.2.1
  
  # State Management
  provider: ^6.1.1
  
  # UI & Animation
  animations: ^2.0.11
  flutter_card_swiper: 7.0.2
  flutter_staggered_animations: ^1.1.1
  
  # Network & API
  http: ^1.1.2
  flutter_dotenv: ^5.1.0
  
  # Image & Media
  cached_network_image: ^3.3.0
  image: ^4.1.3
  flutter_image_compress: ^2.1.0
  
  # Utils
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  cupertino_icons: ^1.0.2
  
  # Fonts
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - .env
    
  # fonts:
  #   - family: NotoSans
  #     fonts:
  #       - asset: assets/fonts/NotoSansKR-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/NotoSansKR-Bold.ttf
  #         weight: 700