name: sona_app
description: SONA - 감정 기반 AI 페르소나 대화 매칭 앱
publish_to: 'none'
version: 1.1.11+40

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.15.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.1.0
  firebase_crashlytics: ^4.0.2
  
  # Authentication
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  
  # State Management
  provider: ^6.1.1
  
  # App Info
  package_info_plus: ^8.0.3
  
  # UI & Animation
  animations: ^2.0.11
  flutter_card_swiper: 7.0.2
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  
  # Network & API
  http: ^1.1.2
  flutter_dotenv: ^5.1.0
  
  # Image & Media
  cached_network_image: ^3.3.0
  image: ^4.1.3
  flutter_image_compress: ^2.1.0
  image_picker: ^1.0.4
  
  # Permissions
  permission_handler: ^11.0.1
  
  # Utils
  intl: ^0.20.2
  haptic_feedback: ^0.5.1+1
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  cupertino_icons: ^1.0.2
  crypto: ^3.0.3
  connectivity_plus: ^5.0.2
  path_provider: ^2.1.1
  
  # In-App Purchase
  in_app_purchase: ^3.2.1
  
  # Fonts
  google_fonts: ^6.1.0
  
  # Push Notifications
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.0.0
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  fake_cloud_firestore: ^3.0.0
  firebase_auth_mocks: ^0.14.2
  google_sign_in_mocks: ^0.3.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/icons/
    - .env
    
  # fonts:
  #   - family: NotoSans
  #     fonts:
  #       - asset: assets/fonts/NotoSansKR-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/NotoSansKR-Bold.ttf

# 앱 아이콘 설정
flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/app_icon.png"
  image_path_ios: "assets/icons/app_icon_ios.png"  # iOS 전용 아이콘 (패딩 없는 버전)
  min_sdk_android: 21
  adaptive_icon_background: "#FF6B9D"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  remove_alpha_ios: true
  background_color_ios: "#FF6B9D"  # iOS 배경색 설정
  #         weight: 700
