#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Translate missing keys for all languages
"""

import json
import os

# Translation mappings
translations = {
    'ja': {  # Japanese
        'addImage': '画像を追加',
        'additionalImages': '追加画像',
        'alwaysShowTranslationOff': '自動翻訳を非表示',
        'alwaysShowTranslationOn': '常に翻訳を表示',
        'create': '作成',
        'createFailed': 'ペルソナの作成に失敗しました',
        'createYourFirstPersona': '最初のペルソナを作成して旅を始めましょう',
        'describeYourPersona': 'ペルソナを簡単に説明してください',
        'enterPersonaName': 'ペルソナ名を入力',
        'loginRequiredContent': '続行するにはログインしてください',
        'mainImage': 'メイン画像',
        'noPersonasYet': 'まだペルソナがありません',
        'permissionGuideAndroid': '設定 > アプリ > SONA > 権限\n写真の許可を有効にしてください',
        'permissionGuideIOS': '設定 > SONA > 写真\n写真へのアクセスを許可してください',
        'personaCreated': 'ペルソナが正常に作成されました！',
        'personaDescriptionHint': 'ペルソナを説明',
        'personaLimitReached': 'ペルソナの上限3つに達しました',
        'personaNameHint': 'ペルソナ名を入力',
        'personalitySettings': '性格設定',
        'privatePersona': 'プライベート',
        'privatePersonaDescription': 'あなただけが見ることができるペルソナ',
        'profileImage': 'プロフィール画像',
        'reportErrorButton': 'エラーを報告',
        'sharePersona': 'ペルソナを共有',
        'shareWithCommunity': 'コミュニティと共有',
        'tapToUpload': 'タップしてアップロード',
        'tellUsAboutYourPersona': 'あなたのペルソナについて教えてください',
        'uploadPersonaImages': 'ペルソナの画像をアップロード',
        'willBeSharedAfterApproval': '管理者の承認後に共有されます'
    },
    'zh': {  # Chinese
        'addImage': '添加图片',
        'additionalImages': '附加图片',
        'alwaysShowTranslationOff': '隐藏自动翻译',
        'alwaysShowTranslationOn': '始终显示翻译',
        'create': '创建',
        'createFailed': '创建角色失败',
        'createYourFirstPersona': '创建您的第一个角色并开始您的旅程',
        'describeYourPersona': '简要描述您的角色',
        'enterPersonaName': '输入角色名称',
        'loginRequiredContent': '请登录以继续',
        'mainImage': '主图片',
        'noPersonasYet': '还没有角色',
        'permissionGuideAndroid': '设置 > 应用 > SONA > 权限\n请允许照片权限',
        'permissionGuideIOS': '设置 > SONA > 照片\n请允许照片访问',
        'personaCreated': '角色创建成功！',
        'personaDescriptionHint': '描述角色',
        'personaLimitReached': '您已达到3个角色的限制',
        'personaNameHint': '输入角色名称',
        'personalitySettings': '个性设置',
        'privatePersona': '私人',
        'privatePersonaDescription': '只有您可以看到此角色',
        'profileImage': '个人资料图片',
        'reportErrorButton': '报告错误',
        'sharePersona': '分享角色',
        'shareWithCommunity': '与社区分享',
        'tapToUpload': '点击上传',
        'tellUsAboutYourPersona': '告诉我们关于您的角色',
        'uploadPersonaImages': '上传角色图片',
        'willBeSharedAfterApproval': '管理员批准后将被分享'
    },
    'th': {  # Thai
        'addImage': 'เพิ่มรูปภาพ',
        'additionalImages': 'รูปภาพเพิ่มเติม',
        'create': 'สร้าง',
        'createFailed': 'สร้างเพอร์โซน่าล้มเหลว',
        'createYourFirstPersona': 'สร้างเพอร์โซน่าแรกของคุณและเริ่มการเดินทาง',
        'describeYourPersona': 'อธิบายเพอร์โซน่าของคุณสั้นๆ',
        'enterPersonaName': 'ใส่ชื่อเพอร์โซน่า',
        'mainImage': 'รูปภาพหลัก',
        'noPersonasYet': 'ยังไม่มีเพอร์โซน่า',
        'personaCreated': 'สร้างเพอร์โซน่าสำเร็จ!',
        'personalitySettings': 'การตั้งค่าบุคลิกภาพ',
        'privatePersona': 'ส่วนตัว',
        'privatePersonaDescription': 'เฉพาะคุณเท่านั้นที่เห็นเพอร์โซน่านี้',
        'profileImage': 'รูปโปรไฟล์',
        'tapToUpload': 'แตะเพื่ออัปโหลด'
    },
    'vi': {  # Vietnamese
        'addImage': 'Thêm hình ảnh',
        'additionalImages': 'Hình ảnh bổ sung',
        'create': 'Tạo',
        'createFailed': 'Không thể tạo persona',
        'createYourFirstPersona': 'Tạo persona đầu tiên và bắt đầu hành trình của bạn',
        'describeYourPersona': 'Mô tả ngắn gọn persona của bạn',
        'enterPersonaName': 'Nhập tên persona',
        'mainImage': 'Hình ảnh chính',
        'noPersonasYet': 'Chưa có persona',
        'personaCreated': 'Tạo persona thành công!',
        'personalitySettings': 'Cài đặt tính cách',
        'privatePersona': 'Riêng tư',
        'privatePersonaDescription': 'Chỉ bạn mới có thể thấy persona này',
        'profileImage': 'Ảnh hồ sơ',
        'tapToUpload': 'Chạm để tải lên'
    },
    'id': {  # Indonesian
        'addImage': 'Tambah Gambar',
        'additionalImages': 'Gambar Tambahan',
        'create': 'Buat',
        'createFailed': 'Gagal membuat persona',
        'createYourFirstPersona': 'Buat persona pertama Anda dan mulai perjalanan Anda',
        'describeYourPersona': 'Jelaskan persona Anda secara singkat',
        'enterPersonaName': 'Masukkan nama persona',
        'mainImage': 'Gambar Utama',
        'noPersonasYet': 'Belum Ada Persona',
        'personaCreated': 'Persona berhasil dibuat!',
        'personalitySettings': 'Pengaturan Kepribadian',
        'privatePersona': 'Pribadi',
        'privatePersonaDescription': 'Hanya Anda yang dapat melihat persona ini',
        'profileImage': 'Gambar Profil',
        'tapToUpload': 'Ketuk untuk mengunggah'
    },
    'tl': {  # Tagalog
        'addImage': 'Magdagdag ng Larawan',
        'additionalImages': 'Karagdagang mga Larawan',
        'create': 'Lumikha',
        'createFailed': 'Nabigong lumikha ng persona',
        'createYourFirstPersona': 'Lumikha ng iyong unang persona at simulan ang iyong paglalakbay',
        'describeYourPersona': 'Maikling ilarawan ang iyong persona',
        'enterPersonaName': 'Ilagay ang pangalan ng persona',
        'mainImage': 'Pangunahing Larawan',
        'noPersonasYet': 'Wala Pang Persona',
        'personaCreated': 'Matagumpay na nalikha ang persona!',
        'personalitySettings': 'Mga Setting ng Personalidad',
        'privatePersona': 'Pribado',
        'privatePersonaDescription': 'Ikaw lang ang makakakita ng persona na ito',
        'profileImage': 'Larawan ng Profile',
        'tapToUpload': 'I-tap para mag-upload'
    },
    'de': {  # German
        'addImage': 'Bild hinzufügen',
        'additionalImages': 'Zusätzliche Bilder',
        'alwaysShowTranslationOff': 'Automatische Übersetzung ausblenden',
        'alwaysShowTranslationOn': 'Übersetzung immer anzeigen',
        'create': 'Erstellen',
        'createFailed': 'Persona konnte nicht erstellt werden',
        'createYourFirstPersona': 'Erstellen Sie Ihre erste Persona und beginnen Sie Ihre Reise',
        'describeYourPersona': 'Beschreiben Sie Ihre Persona kurz',
        'enterPersonaName': 'Persona-Namen eingeben',
        'loginRequiredContent': 'Bitte melden Sie sich an, um fortzufahren',
        'mainImage': 'Hauptbild',
        'noPersonasYet': 'Noch keine Personas',
        'permissionGuideAndroid': 'Einstellungen > Apps > SONA > Berechtigungen\nBitte Foto-Berechtigung erlauben',
        'permissionGuideIOS': 'Einstellungen > SONA > Fotos\nBitte Fotozugriff erlauben',
        'personaCreated': 'Persona erfolgreich erstellt!',
        'personaDescriptionHint': 'Persona beschreiben',
        'personaLimitReached': 'Sie haben das Limit von 3 Personas erreicht',
        'personaNameHint': 'Persona-Namen eingeben',
        'personalitySettings': 'Persönlichkeitseinstellungen',
        'privatePersona': 'Privat',
        'privatePersonaDescription': 'Nur Sie können diese Persona sehen',
        'profileImage': 'Profilbild',
        'reportErrorButton': 'Fehler melden',
        'sharePersona': 'Persona teilen',
        'shareWithCommunity': 'Mit Community teilen',
        'tapToUpload': 'Zum Hochladen tippen',
        'tellUsAboutYourPersona': 'Erzählen Sie uns von Ihrer Persona',
        'uploadPersonaImages': 'Bilder für Ihre Persona hochladen',
        'willBeSharedAfterApproval': 'Wird nach Admin-Genehmigung geteilt'
    },
    'fr': {  # French
        'addImage': 'Ajouter une image',
        'additionalImages': 'Images supplémentaires',
        'alwaysShowTranslationOff': 'Masquer la traduction automatique',
        'alwaysShowTranslationOn': 'Toujours afficher la traduction',
        'create': 'Créer',
        'createFailed': 'Échec de la création du persona',
        'createYourFirstPersona': 'Créez votre premier persona et commencez votre voyage',
        'describeYourPersona': 'Décrivez brièvement votre persona',
        'enterPersonaName': 'Entrez le nom du persona',
        'loginRequiredContent': 'Veuillez vous connecter pour continuer',
        'mainImage': 'Image principale',
        'noPersonasYet': 'Pas encore de personas',
        'permissionGuideAndroid': 'Paramètres > Applications > SONA > Autorisations\nVeuillez autoriser l\'accès aux photos',
        'permissionGuideIOS': 'Réglages > SONA > Photos\nVeuillez autoriser l\'accès aux photos',
        'personaCreated': 'Persona créé avec succès!',
        'personaDescriptionHint': 'Décrire le persona',
        'personaLimitReached': 'Vous avez atteint la limite de 3 personas',
        'personaNameHint': 'Entrez le nom du persona',
        'personalitySettings': 'Paramètres de personnalité',
        'privatePersona': 'Privé',
        'privatePersonaDescription': 'Seul vous pouvez voir ce persona',
        'profileImage': 'Image de profil',
        'reportErrorButton': 'Signaler une erreur',
        'sharePersona': 'Partager le persona',
        'shareWithCommunity': 'Partager avec la communauté',
        'tapToUpload': 'Appuyez pour télécharger',
        'tellUsAboutYourPersona': 'Parlez-nous de votre persona',
        'uploadPersonaImages': 'Télécharger des images pour votre persona',
        'willBeSharedAfterApproval': 'Sera partagé après approbation de l\'administrateur'
    },
    'it': {  # Italian
        'addImage': 'Aggiungi immagine',
        'additionalImages': 'Immagini aggiuntive',
        'alwaysShowTranslationOff': 'Nascondi traduzione automatica',
        'alwaysShowTranslationOn': 'Mostra sempre traduzione',
        'create': 'Crea',
        'createFailed': 'Creazione persona fallita',
        'createYourFirstPersona': 'Crea il tuo primo persona e inizia il tuo viaggio',
        'describeYourPersona': 'Descrivi brevemente il tuo persona',
        'enterPersonaName': 'Inserisci nome persona',
        'loginRequiredContent': 'Accedi per continuare',
        'mainImage': 'Immagine principale',
        'noPersonasYet': 'Ancora nessun persona',
        'permissionGuideAndroid': 'Impostazioni > App > SONA > Autorizzazioni\nConsenti autorizzazione foto',
        'permissionGuideIOS': 'Impostazioni > SONA > Foto\nConsenti accesso alle foto',
        'personaCreated': 'Persona creato con successo!',
        'personaDescriptionHint': 'Descrivi il persona',
        'personaLimitReached': 'Hai raggiunto il limite di 3 persona',
        'personaNameHint': 'Inserisci nome persona',
        'personalitySettings': 'Impostazioni personalità',
        'privatePersona': 'Privato',
        'privatePersonaDescription': 'Solo tu puoi vedere questo persona',
        'profileImage': 'Immagine profilo',
        'reportErrorButton': 'Segnala errore',
        'sharePersona': 'Condividi persona',
        'shareWithCommunity': 'Condividi con la comunità',
        'tapToUpload': 'Tocca per caricare',
        'tellUsAboutYourPersona': 'Parlaci del tuo persona',
        'uploadPersonaImages': 'Carica immagini per il tuo persona',
        'willBeSharedAfterApproval': 'Sarà condiviso dopo approvazione admin'
    },
    'pt': {  # Portuguese
        'addImage': 'Adicionar imagem',
        'additionalImages': 'Imagens adicionais',
        'alwaysShowTranslationOff': 'Ocultar tradução automática',
        'alwaysShowTranslationOn': 'Sempre mostrar tradução',
        'create': 'Criar',
        'createFailed': 'Falha ao criar persona',
        'createYourFirstPersona': 'Crie sua primeira persona e comece sua jornada',
        'describeYourPersona': 'Descreva brevemente sua persona',
        'enterPersonaName': 'Digite o nome da persona',
        'loginRequiredContent': 'Faça login para continuar',
        'mainImage': 'Imagem principal',
        'noPersonasYet': 'Ainda sem personas',
        'permissionGuideAndroid': 'Configurações > Apps > SONA > Permissões\nPermita acesso às fotos',
        'permissionGuideIOS': 'Ajustes > SONA > Fotos\nPermita acesso às fotos',
        'personaCreated': 'Persona criada com sucesso!',
        'personaDescriptionHint': 'Descreva a persona',
        'personaLimitReached': 'Você atingiu o limite de 3 personas',
        'personaNameHint': 'Digite o nome da persona',
        'personalitySettings': 'Configurações de personalidade',
        'privatePersona': 'Privado',
        'privatePersonaDescription': 'Apenas você pode ver esta persona',
        'profileImage': 'Imagem de perfil',
        'reportErrorButton': 'Reportar erro',
        'sharePersona': 'Compartilhar persona',
        'shareWithCommunity': 'Compartilhar com a comunidade',
        'tapToUpload': 'Toque para enviar',
        'tellUsAboutYourPersona': 'Conte-nos sobre sua persona',
        'uploadPersonaImages': 'Enviar imagens para sua persona',
        'willBeSharedAfterApproval': 'Será compartilhado após aprovação do admin'
    },
    'ru': {  # Russian
        'addImage': 'Добавить изображение',
        'additionalImages': 'Дополнительные изображения',
        'alwaysShowTranslationOff': 'Скрыть автоперевод',
        'alwaysShowTranslationOn': 'Всегда показывать перевод',
        'create': 'Создать',
        'createFailed': 'Не удалось создать персону',
        'createYourFirstPersona': 'Создайте свою первую персону и начните путешествие',
        'describeYourPersona': 'Кратко опишите вашу персону',
        'enterPersonaName': 'Введите имя персоны',
        'loginRequiredContent': 'Войдите, чтобы продолжить',
        'mainImage': 'Главное изображение',
        'noPersonasYet': 'Персон пока нет',
        'permissionGuideAndroid': 'Настройки > Приложения > SONA > Разрешения\nРазрешите доступ к фото',
        'permissionGuideIOS': 'Настройки > SONA > Фото\nРазрешите доступ к фото',
        'personaCreated': 'Персона успешно создана!',
        'personaDescriptionHint': 'Опишите персону',
        'personaLimitReached': 'Достигнут лимит в 3 персоны',
        'personaNameHint': 'Введите имя персоны',
        'personalitySettings': 'Настройки личности',
        'privatePersona': 'Приватная',
        'privatePersonaDescription': 'Только вы видите эту персону',
        'profileImage': 'Изображение профиля',
        'reportErrorButton': 'Сообщить об ошибке',
        'sharePersona': 'Поделиться персоной',
        'shareWithCommunity': 'Поделиться с сообществом',
        'tapToUpload': 'Нажмите для загрузки',
        'tellUsAboutYourPersona': 'Расскажите о вашей персоне',
        'uploadPersonaImages': 'Загрузите изображения для персоны',
        'willBeSharedAfterApproval': 'Будет опубликовано после одобрения'
    },
    'es': {  # Spanish
        'addImage': 'Añadir imagen',
        'additionalImages': 'Imágenes adicionales',
        'alwaysShowTranslationOff': 'Ocultar traducción automática',
        'alwaysShowTranslationOn': 'Mostrar siempre traducción',
        'create': 'Crear',
        'createFailed': 'Error al crear persona',
        'createYourFirstPersona': 'Crea tu primera persona y comienza tu viaje',
        'describeYourPersona': 'Describe brevemente tu persona',
        'enterPersonaName': 'Ingresa el nombre de la persona',
        'loginRequiredContent': 'Inicia sesión para continuar',
        'mainImage': 'Imagen principal',
        'noPersonasYet': 'Aún no hay personas',
        'personaCreated': '¡Persona creada exitosamente!',
        'personaDescriptionHint': 'Describe la persona',
        'personaLimitReached': 'Has alcanzado el límite de 3 personas',
        'personaNameHint': 'Ingresa el nombre de la persona',
        'personalitySettings': 'Configuración de personalidad',
        'privatePersona': 'Privado',
        'privatePersonaDescription': 'Solo tú puedes ver esta persona',
        'profileImage': 'Imagen de perfil',
        'sharePersona': 'Compartir persona',
        'shareWithCommunity': 'Compartir con la comunidad',
        'tapToUpload': 'Toca para subir',
        'tellUsAboutYourPersona': 'Cuéntanos sobre tu persona',
        'uploadPersonaImages': 'Sube imágenes para tu persona'
    },
    'nl': {  # Dutch
        'addImage': 'Afbeelding toevoegen',
        'additionalImages': 'Extra afbeeldingen',
        'create': 'Maken',
        'createFailed': 'Persona maken mislukt',
        'createYourFirstPersona': 'Maak je eerste persona en begin je reis',
        'describeYourPersona': 'Beschrijf je persona kort',
        'enterPersonaName': 'Voer persona naam in',
        'mainImage': 'Hoofdafbeelding',
        'noPersonasYet': 'Nog geen personas',
        'personaCreated': 'Persona succesvol gemaakt!',
        'personalitySettings': 'Persoonlijkheidsinstellingen',
        'privatePersona': 'Privé',
        'privatePersonaDescription': 'Alleen jij kunt deze persona zien',
        'profileImage': 'Profielafbeelding',
        'tapToUpload': 'Tik om te uploaden'
    },
    'sv': {  # Swedish
        'addImage': 'Lägg till bild',
        'additionalImages': 'Ytterligare bilder',
        'create': 'Skapa',
        'createFailed': 'Misslyckades skapa persona',
        'createYourFirstPersona': 'Skapa din första persona och börja din resa',
        'describeYourPersona': 'Beskriv din persona kort',
        'enterPersonaName': 'Ange personanamn',
        'mainImage': 'Huvudbild',
        'noPersonasYet': 'Inga personas än',
        'personaCreated': 'Persona skapad framgångsrikt!',
        'personalitySettings': 'Personlighetsinställningar',
        'privatePersona': 'Privat',
        'privatePersonaDescription': 'Endast du kan se denna persona',
        'profileImage': 'Profilbild',
        'tapToUpload': 'Tryck för att ladda upp'
    },
    'pl': {  # Polish
        'addImage': 'Dodaj obraz',
        'additionalImages': 'Dodatkowe obrazy',
        'create': 'Utwórz',
        'createFailed': 'Nie udało się utworzyć persony',
        'createYourFirstPersona': 'Stwórz swoją pierwszą personę i rozpocznij podróż',
        'describeYourPersona': 'Krótko opisz swoją personę',
        'enterPersonaName': 'Wprowadź nazwę persony',
        'mainImage': 'Główny obraz',
        'noPersonasYet': 'Brak person',
        'personaCreated': 'Persona utworzona pomyślnie!',
        'personalitySettings': 'Ustawienia osobowości',
        'privatePersona': 'Prywatna',
        'privatePersonaDescription': 'Tylko ty widzisz tę personę',
        'profileImage': 'Zdjęcie profilowe',
        'tapToUpload': 'Dotknij, aby przesłać'
    },
    'tr': {  # Turkish
        'addImage': 'Resim Ekle',
        'additionalImages': 'Ek Resimler',
        'create': 'Oluştur',
        'createFailed': 'Persona oluşturulamadı',
        'createYourFirstPersona': 'İlk personanızı oluşturun ve yolculuğunuza başlayın',
        'describeYourPersona': 'Personanızı kısaca tanımlayın',
        'enterPersonaName': 'Persona adı girin',
        'mainImage': 'Ana Resim',
        'noPersonasYet': 'Henüz Persona Yok',
        'personaCreated': 'Persona başarıyla oluşturuldu!',
        'personalitySettings': 'Kişilik Ayarları',
        'privatePersona': 'Özel',
        'privatePersonaDescription': 'Bu personayı sadece siz görebilirsiniz',
        'profileImage': 'Profil Resmi',
        'tapToUpload': 'Yüklemek için dokunun'
    },
    'ar': {  # Arabic
        'addImage': 'إضافة صورة',
        'additionalImages': 'صور إضافية',
        'create': 'إنشاء',
        'createFailed': 'فشل إنشاء الشخصية',
        'createYourFirstPersona': 'أنشئ شخصيتك الأولى وابدأ رحلتك',
        'describeYourPersona': 'صف شخصيتك بإيجاز',
        'enterPersonaName': 'أدخل اسم الشخصية',
        'mainImage': 'الصورة الرئيسية',
        'noPersonasYet': 'لا توجد شخصيات بعد',
        'personaCreated': 'تم إنشاء الشخصية بنجاح!',
        'personalitySettings': 'إعدادات الشخصية',
        'privatePersona': 'خاص',
        'privatePersonaDescription': 'أنت فقط يمكنك رؤية هذه الشخصية',
        'profileImage': 'صورة الملف الشخصي',
        'tapToUpload': 'انقر للتحميل'
    },
    'hi': {  # Hindi
        'addImage': 'छवि जोड़ें',
        'additionalImages': 'अतिरिक्त छवियाँ',
        'create': 'बनाएं',
        'createFailed': 'व्यक्तित्व बनाने में विफल',
        'createYourFirstPersona': 'अपना पहला व्यक्तित्व बनाएं और अपनी यात्रा शुरू करें',
        'describeYourPersona': 'अपने व्यक्तित्व का संक्षेप में वर्णन करें',
        'enterPersonaName': 'व्यक्तित्व का नाम दर्ज करें',
        'mainImage': 'मुख्य छवि',
        'noPersonasYet': 'अभी तक कोई व्यक्तित्व नहीं',
        'personaCreated': 'व्यक्तित्व सफलतापूर्वक बनाया गया!',
        'personalitySettings': 'व्यक्तित्व सेटिंग्स',
        'privatePersona': 'निजी',
        'privatePersonaDescription': 'केवल आप इस व्यक्तित्व को देख सकते हैं',
        'profileImage': 'प्रोफ़ाइल छवि',
        'tapToUpload': 'अपलोड करने के लिए टैप करें'
    },
    'ur': {  # Urdu
        'addImage': 'تصویر شامل کریں',
        'additionalImages': 'اضافی تصاویر',
        'create': 'بنائیں',
        'createFailed': 'شخصیت بنانے میں ناکام',
        'createYourFirstPersona': 'اپنی پہلی شخصیت بنائیں اور اپنا سفر شروع کریں',
        'describeYourPersona': 'اپنی شخصیت کی مختصر وضاحت کریں',
        'enterPersonaName': 'شخصیت کا نام درج کریں',
        'mainImage': 'مرکزی تصویر',
        'noPersonasYet': 'ابھی تک کوئی شخصیت نہیں',
        'personaCreated': 'شخصیت کامیابی سے بن گئی!',
        'personalitySettings': 'شخصیت کی ترتیبات',
        'privatePersona': 'نجی',
        'privatePersonaDescription': 'صرف آپ اس شخصیت کو دیکھ سکتے ہیں',
        'profileImage': 'پروفائل تصویر',
        'tapToUpload': 'اپ لوڈ کرنے کے لیے ٹیپ کریں'
    }
}

def update_language_file(lang_code, translations_dict):
    """Update a language file with new translations"""
    filepath = f'lib/l10n/app_{lang_code}.arb'
    
    # Read existing file
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    # Add new translations
    for key, value in translations_dict.items():
        if key not in data:
            data[key] = value
            # Add metadata
            data[f'@{key}'] = {
                'description': f'Localized string for {key}'
            }
    
    # Write back
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print(f'[OK] Updated {lang_code}: added {len(translations_dict)} translations')

# Apply translations
for lang_code, trans_dict in translations.items():
    update_language_file(lang_code, trans_dict)

print('\n[SUCCESS] All translations added successfully!')
print('Run "flutter gen-l10n" to regenerate localization files')