// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDAB8M2j6qL5V0Emg7WeIy3PionY5aKeQ',
    appId: '1:874385422837:web:abc123web567890',
    messagingSenderId: '874385422837',
    projectId: 'sona-app-89598',
    authDomain: 'sona-app-89598.firebaseapp.com',
    storageBucket: 'sona-app-89598.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDAB8M2j6qL5V0Emg7WeIy3PionY5aKeQ',
    appId: '1:874385422837:android:2c30f090413a7f7dabc8bc',
    messagingSenderId: '874385422837',
    projectId: 'sona-app-89598',
    authDomain: 'sona-app-89598.firebaseapp.com',
    storageBucket: 'sona-app-89598.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDAB8M2j6qL5V0Emg7WeIy3PionY5aKeQ',
    appId: '1:874385422837:ios:abc123ios567890',
    messagingSenderId: '874385422837',
    projectId: 'sona-app-89598',
    authDomain: 'sona-app-89598.firebaseapp.com',
    storageBucket: 'sona-app-89598.firebasestorage.app',
    iosClientId: '874385422837-iosapp1234567890.apps.googleusercontent.com',
    iosBundleId: 'com.nohbrother.teamsona.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDAB8M2j6qL5V0Emg7WeIy3PionY5aKeQ',
    appId: '1:874385422837:macos:abc123macos567890',
    messagingSenderId: '874385422837',
    projectId: 'sona-app-89598',
    authDomain: 'sona-app-89598.firebaseapp.com',
    storageBucket: 'sona-app-89598.firebasestorage.app',
    iosClientId: '874385422837-macosapp1234567890.apps.googleusercontent.com',
    iosBundleId: 'com.nohbrother.teamsona.chatapp',
  );
}