#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Indonesian (id-ID) Translation Script for SONA App
Translates Korean ARB file to Indonesian
"""

import json
from pathlib import Path

def translate_to_indonesian():
    """Translate Korean ARB to Indonesian"""
    
    # Paths
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    l10n_dir = project_root / "sona_app" / "lib" / "l10n"
    
    ko_arb_path = l10n_dir / "app_ko.arb"
    id_arb_path = l10n_dir / "app_id.arb"
    
    # Read Korean ARB
    with open(ko_arb_path, 'r', encoding='utf-8') as f:
        ko_data = json.load(f)
    
    # Indonesian translations (manual for accuracy)
    id_translations = {
        "appName": "SONA",
        "loading": "Memuat...",
        "error": "Kesalahan",
        "retry": "Coba lagi",
        "cancel": "Batal",
        "confirm": "Konfirmasi",
        "next": "Berikutnya",
        "skip": "Lewati",
        "done": "Selesai",
        "save": "Simpan",
        "delete": "Hapus",
        "edit": "Edit",
        "close": "Tutup",
        "search": "Cari",
        "filter": "Filter",
        "sort": "Urutkan",
        "refresh": "Segarkan",
        "yes": "Ya",
        "no": "Tidak",
        "you": "Anda",
        "login": "Masuk",
        "signup": "Daftar",
        "meetAIPersonas": "Temui Persona AI",
        "welcomeMessage": "Selamat datang💕",
        "loginSignup": "Masuk/Daftar",
        "logout": "Keluar",
        "email": "Email",
        "password": "Kata sandi",
        "confirmPassword": "Konfirmasi kata sandi",
        "nickname": "Nama panggilan",
        "forgotPassword": "Lupa kata sandi?",
        "alreadyHaveAccount": "Sudah punya akun?",
        "dontHaveAccount": "Belum punya akun?",
        "continueWithGoogle": "Lanjutkan dengan Google",
        "continueWithApple": "Lanjutkan dengan Apple",
        "or": "atau",
        "termsOfService": "Ketentuan Layanan",
        "privacyPolicy": "Kebijakan Privasi",
        "agreeToTerms": "Dengan mendaftar, Anda menyetujui {terms} dan {privacy} kami",
        "emailRequired": "Silakan masukkan email",
        "passwordRequired": "Silakan masukkan kata sandi",
        "nicknameRequired": "Silakan masukkan nama panggilan",
        "invalidEmail": "Email tidak valid",
        "passwordTooShort": "Kata sandi minimal 6 karakter",
        "passwordMismatch": "Kata sandi tidak cocok",
        "loginFailed": "Gagal masuk",
        "signupFailed": "Gagal mendaftar",
        "emailAlreadyInUse": "Email sudah digunakan",
        "weakPassword": "Kata sandi terlalu lemah",
        "userNotFound": "Pengguna tidak ditemukan",
        "wrongPassword": "Kata sandi salah",
        "networkError": "Kesalahan jaringan",
        "unknownError": "Kesalahan tidak diketahui",
        "profile": "Profil",
        "settings": "Pengaturan",
        "notifications": "Notifikasi",
        "language": "Bahasa",
        "theme": "Tema",
        "darkMode": "Mode gelap",
        "lightMode": "Mode terang",
        "systemDefault": "Default sistem",
        "about": "Tentang",
        "version": "Versi",
        "contactUs": "Hubungi kami",
        "reportBug": "Laporkan bug",
        "rateApp": "Beri nilai aplikasi",
        "shareApp": "Bagikan aplikasi",
        "chat": "Obrolan",
        "personas": "Persona",
        "store": "Toko",
        "heart": "Hati",
        "hearts": "Hati",
        "coin": "Koin",
        "coins": "Koin",
        "level": "Level",
        "experience": "Pengalaman",
        "achievement": "Pencapaian",
        "achievements": "Pencapaian",
        "reward": "Hadiah",
        "rewards": "Hadiah",
        "daily": "Harian",
        "weekly": "Mingguan",
        "monthly": "Bulanan",
        "newMessage": "Pesan baru",
        "typeMessage": "Ketik pesan...",
        "send": "Kirim",
        "sending": "Mengirim...",
        "sent": "Terkirim",
        "delivered": "Terkirim",
        "read": "Dibaca",
        "online": "Online",
        "offline": "Offline",
        "lastSeen": "Terakhir terlihat",
        "typing": "Mengetik...",
        "recording": "Merekam...",
        "photo": "Foto",
        "camera": "Kamera",
        "gallery": "Galeri",
        "file": "File",
        "location": "Lokasi",
        "voice": "Suara",
        "video": "Video",
        "monday": "Senin",
        "tuesday": "Selasa",
        "wednesday": "Rabu",
        "thursday": "Kamis",
        "friday": "Jumat",
        "saturday": "Sabtu",
        "sunday": "Minggu",
        "january": "Januari",
        "february": "Februari",
        "march": "Maret",
        "april": "April",
        "may": "Mei",
        "june": "Juni",
        "july": "Juli",
        "august": "Agustus",
        "september": "September",
        "october": "Oktober",
        "november": "November",
        "december": "Desember",
        "today": "Hari ini",
        "yesterday": "Kemarin",
        "tomorrow": "Besok",
        "now": "Sekarang",
        "justNow": "Baru saja",
        "minutesAgo": "{count} menit yang lalu",
        "hoursAgo": "{count} jam yang lalu",
        "daysAgo": "{count} hari yang lalu",
        "weeksAgo": "{count} minggu yang lalu",
        "monthsAgo": "{count} bulan yang lalu",
        "yearsAgo": "{count} tahun yang lalu",
        
        # Additional SONA-specific translations
        "personaSelection": "Pilihan Persona",
        "selectYourPersona": "Pilih persona Anda",
        "personalityTraits": "Sifat kepribadian",
        "conversationStyle": "Gaya percakapan",
        "interests": "Minat",
        "startChat": "Mulai obrolan",
        "endChat": "Akhiri obrolan",
        "clearChat": "Hapus obrolan",
        "chatHistory": "Riwayat obrolan",
        "noMessages": "Belum ada pesan",
        "noPersonasAvailable": "Tidak ada persona tersedia",
        "loadingPersonas": "Memuat persona...",
        "personaLocked": "Persona terkunci",
        "unlockWithHearts": "Buka dengan {hearts} hati",
        "insufficientHearts": "Hati tidak cukup",
        "purchaseHearts": "Beli hati",
        "earnHearts": "Dapatkan hati",
        "dailyReward": "Hadiah harian",
        "claimReward": "Klaim hadiah",
        "rewardClaimed": "Hadiah diklaim",
        "comeBackTomorrow": "Kembali besok",
        "personalityTest": "Tes kepribadian",
        "takeTest": "Ikuti tes",
        "retakeTest": "Ulangi tes",
        "testResults": "Hasil tes",
        "yourPersonalityType": "Tipe kepribadian Anda",
        "matchingPersonas": "Persona yang cocok",
        "recommendedForYou": "Direkomendasikan untuk Anda",
        "popularPersonas": "Persona populer",
        "newPersonas": "Persona baru",
        "favoritePersonas": "Persona favorit",
        "blockedPersonas": "Persona yang diblokir",
        "unblockPersona": "Buka blokir persona",
        "blockPersona": "Blokir persona",
        "reportPersona": "Laporkan persona",
        "reportReason": "Alasan laporan",
        "reportSubmitted": "Laporan terkirim",
        "changeNickname": "Ubah nama panggilan",
        "changePassword": "Ubah kata sandi",
        "deleteAccount": "Hapus akun",
        "accountDeleted": "Akun dihapus",
        "confirmDelete": "Anda yakin ingin menghapus akun?",
        "cannotBeUndone": "Tindakan ini tidak dapat dibatalkan",
        "profileUpdated": "Profil diperbarui",
        "settingsUpdated": "Pengaturan diperbarui",
        "notificationsEnabled": "Notifikasi diaktifkan",
        "notificationsDisabled": "Notifikasi dinonaktifkan",
        "soundEnabled": "Suara diaktifkan",
        "soundDisabled": "Suara dinonaktifkan",
        "vibrationEnabled": "Getaran diaktifkan",
        "vibrationDisabled": "Getaran dinonaktifkan",
        "dataUsage": "Penggunaan data",
        "cacheCleared": "Cache dihapus",
        "clearCache": "Hapus cache",
        "storageUsed": "Penyimpanan terpakai",
        "availableStorage": "Penyimpanan tersedia",
        "backupData": "Cadangkan data",
        "restoreData": "Pulihkan data",
        "exportChat": "Ekspor obrolan",
        "importChat": "Impor obrolan",
        "connectionLost": "Koneksi terputus",
        "reconnecting": "Menghubungkan kembali...",
        "reconnected": "Terhubung kembali",
        "checkingForUpdates": "Memeriksa pembaruan...",
        "updateAvailable": "Pembaruan tersedia",
        "updateNow": "Perbarui sekarang",
        "updateLater": "Nanti",
        "downloadingUpdate": "Mengunduh pembaruan...",
        "installingUpdate": "Memasang pembaruan...",
        "updateComplete": "Pembaruan selesai",
        "restartRequired": "Perlu restart",
        "restartNow": "Restart sekarang",
        "restartLater": "Nanti",
        
        # Premium/Purchase related
        "premium": "Premium",
        "upgradeToPremium": "Upgrade ke Premium",
        "premiumBenefits": "Manfaat Premium",
        "unlimitedHearts": "Hati tak terbatas",
        "unlimitedChats": "Obrolan tak terbatas",
        "exclusivePersonas": "Persona eksklusif",
        "adFree": "Tanpa iklan",
        "prioritySupport": "Dukungan prioritas",
        "monthlySubscription": "Langganan bulanan",
        "yearlySubscription": "Langganan tahunan",
        "lifetimeAccess": "Akses seumur hidup",
        "purchaseSuccessful": "Pembelian berhasil",
        "purchaseFailed": "Pembelian gagal",
        "restorePurchases": "Pulihkan pembelian",
        "purchasesRestored": "Pembelian dipulihkan",
        "noPurchasesToRestore": "Tidak ada pembelian",
        
        # Error messages
        "somethingWentWrong": "Terjadi kesalahan",
        "pleaseTryAgain": "Silakan coba lagi",
        "errorLoadingData": "Error memuat data",
        "errorSavingData": "Error menyimpan data",
        "errorDeletingData": "Error menghapus data",
        "noInternetConnection": "Tidak ada koneksi internet",
        "serverError": "Error server",
        "requestTimeout": "Waktu permintaan habis",
        "invalidData": "Data tidak valid",
        "accessDenied": "Akses ditolak",
        "sessionExpired": "Sesi berakhir",
        "pleaseLoginAgain": "Silakan masuk lagi",
        
        # Success messages
        "success": "Berhasil",
        "savedSuccessfully": "Berhasil disimpan",
        "deletedSuccessfully": "Berhasil dihapus",
        "updatedSuccessfully": "Berhasil diperbarui",
        "sentSuccessfully": "Berhasil dikirim",
        
        # Confirmation dialogs
        "areYouSure": "Anda yakin?",
        "confirmAction": "Konfirmasi tindakan",
        "confirmLogout": "Anda yakin ingin keluar?",
        "confirmClearChat": "Anda yakin ingin menghapus obrolan?",
        "confirmBlockPersona": "Anda yakin ingin memblokir persona ini?",
        
        # Onboarding
        "welcomeToSona": "Selamat datang di SONA",
        "getStarted": "Mulai",
        "nextStep": "Langkah berikutnya",
        "previousStep": "Langkah sebelumnya",
        "completeSetup": "Selesaikan pengaturan",
        "skipSetup": "Lewati pengaturan",
        "onboardingTitle1": "Temui AI pendamping sempurna Anda",
        "onboardingDesc1": "Temukan persona AI yang dipersonalisasi sesuai kepribadian Anda",
        "onboardingTitle2": "Percakapan alami",
        "onboardingDesc2": "Nikmati percakapan bermakna dengan AI yang memahami Anda",
        "onboardingTitle3": "Berkembang bersama",
        "onboardingDesc3": "Bangun koneksi yang lebih dalam dengan setiap percakapan",
        
        # Personality traits
        "introvert": "Introvert",
        "extrovert": "Ekstrovert",
        "thinking": "Pemikir",
        "feeling": "Perasa",
        "judging": "Penilai",
        "perceiving": "Pengamat",
        "sensing": "Pengindera",
        "intuition": "Intuitif",
        
        # Chat emotions/reactions
        "happy": "Senang",
        "sad": "Sedih",
        "angry": "Marah",
        "surprised": "Terkejut",
        "love": "Cinta",
        "confused": "Bingung",
        "excited": "Bersemangat",
        "worried": "Khawatir",
        "grateful": "Bersyukur",
        "proud": "Bangga",
        
        # Time periods
        "morning": "Pagi",
        "afternoon": "Siang",
        "evening": "Sore",
        "night": "Malam",
        "weekend": "Akhir pekan",
        "weekday": "Hari kerja",
        
        # Special features
        "voiceCall": "Panggilan suara",
        "videoCall": "Panggilan video",
        "shareScreen": "Bagikan layar",
        "sendGift": "Kirim hadiah",
        "playGame": "Main game",
        "watchTogether": "Nonton bersama",
        "listenMusic": "Dengar musik",
        "readStory": "Baca cerita",
        
        # Settings categories
        "accountSettings": "Pengaturan akun",
        "chatSettings": "Pengaturan obrolan",
        "notificationSettings": "Pengaturan notifikasi",
        "privacySettings": "Pengaturan privasi",
        "appearanceSettings": "Pengaturan tampilan",
        "languageSettings": "Pengaturan bahasa",
        "dataSettings": "Pengaturan data",
        "helpAndSupport": "Bantuan & Dukungan",
        
        # Help/Support
        "faq": "FAQ",
        "userGuide": "Panduan pengguna",
        "contactSupport": "Hubungi dukungan",
        "feedbackAndSuggestions": "Masukan & Saran",
        "reportProblem": "Laporkan masalah",
        "requestFeature": "Minta fitur",
        
        # Legal
        "terms": "Ketentuan",
        "privacy": "Privasi",
        "licenses": "Lisensi",
        "copyright": "Hak cipta",
        "disclaimer": "Penafian",
        
        # Additional UI elements
        "pull_to_refresh": "Tarik untuk menyegarkan",
        "release_to_refresh": "Lepas untuk menyegarkan",
        "refreshing": "Menyegarkan...",
        "load_more": "Muat lebih banyak",
        "loading_more": "Memuat lebih banyak...",
        "no_more_data": "Tidak ada data lagi",
        "empty_state": "Tidak ada apa-apa di sini",
        "try_again_later": "Coba lagi nanti",
        "coming_soon": "Segera hadir",
        "beta": "Beta",
        "new": "Baru",
        "updated": "Diperbarui",
        "featured": "Unggulan",
        "trending": "Trending",
        "hot": "Hot",
        "limited": "Terbatas",
        "exclusive": "Eksklusif",
        "special": "Spesial",
        "recommended": "Direkomendasikan",
        "popular": "Populer",
        "verified": "Terverifikasi",
        "official": "Resmi",
        
        # Gender
        "male": "Laki-laki",
        "female": "Perempuan",
        "other": "Lainnya",
        "preferNotToSay": "Tidak ingin menyebutkan",
        
        # Age
        "ageRange": "Rentang usia",
        "under18": "Di bawah 18",
        "18to24": "18-24",
        "25to34": "25-34",
        "35to44": "35-44",
        "45to54": "45-54",
        "55plus": "55+",
        
        # Relationship status
        "single": "Lajang",
        "inRelationship": "Berpacaran",
        "married": "Menikah",
        "divorced": "Bercerai",
        "widowed": "Duda/Janda",
        "complicated": "Rumit",
        
        # Mood/Status
        "available": "Tersedia",
        "busy": "Sibuk",
        "away": "Pergi",
        "doNotDisturb": "Jangan ganggu",
        "invisible": "Tak terlihat",
        
        # Actions
        "like": "Suka",
        "unlike": "Batal suka",
        "favorite": "Favorit",
        "unfavorite": "Batal favorit",
        "follow": "Ikuti",
        "unfollow": "Berhenti ikuti",
        "share": "Bagikan",
        "copy": "Salin",
        "paste": "Tempel",
        "cut": "Potong",
        "undo": "Urungkan",
        "redo": "Ulangi",
        "selectAll": "Pilih semua",
        "deselectAll": "Batal pilih semua",
        
        # Permissions
        "allowAccess": "Izinkan akses",
        "denyAccess": "Tolak akses",
        "grantPermission": "Berikan izin",
        "revokePermission": "Cabut izin",
        "cameraPermission": "Izin kamera",
        "microphonePermission": "Izin mikrofon",
        "locationPermission": "Izin lokasi",
        "notificationPermission": "Izin notifikasi",
        "storagePermission": "Izin penyimpanan",
        "contactsPermission": "Izin kontak",
        
        # Validation messages
        "fieldRequired": "Bidang ini wajib diisi",
        "invalidFormat": "Format tidak valid",
        "tooShort": "Terlalu pendek",
        "tooLong": "Terlalu panjang",
        "invalidCharacters": "Karakter tidak valid",
        "alreadyExists": "Sudah ada",
        "notFound": "Tidak ditemukan",
        "expired": "Kedaluwarsa",
        "invalid": "Tidak valid",
        "required": "Wajib",
        "optional": "Opsional",
        
        # Navigation
        "home": "Beranda",
        "back": "Kembali",
        "forward": "Maju",
        "menu": "Menu",
        "more": "Lainnya",
        "less": "Lebih sedikit",
        "showMore": "Tampilkan lebih banyak",
        "showLess": "Tampilkan lebih sedikit",
        "viewAll": "Lihat semua",
        "viewDetails": "Lihat detail",
        "goBack": "Kembali",
        "goToHome": "Ke beranda",
        "goToSettings": "Ke pengaturan",
        "goToProfile": "Ke profil",
        
        # Formats
        "dateFormat": "dd/MM/yyyy",
        "timeFormat": "HH:mm",
        "dateTimeFormat": "dd/MM/yyyy HH:mm",
        "currency": "Rp",
        "currencySymbol": "Rp",
        "decimalSeparator": ",",
        "thousandsSeparator": ".",
        
        # Special Indonesian phrases
        "selamatDatang": "Selamat datang",
        "sampaiJumpa": "Sampai jumpa",
        "terimakasih": "Terima kasih",
        "maaf": "Maaf",
        "samaSama": "Sama-sama",
        "senangBertemu": "Senang bertemu Anda",
        "selamatPagi": "Selamat pagi",
        "selamatSiang": "Selamat siang",
        "selamatSore": "Selamat sore",
        "selamatMalam": "Selamat malam",
        "selamatTidur": "Selamat tidur"
    }
    
    # Create Indonesian ARB with proper structure
    id_data = {"@@locale": "id"}
    
    # Process all keys from Korean ARB
    for key, value in ko_data.items():
        if key.startswith("@@"):
            if key == "@@locale":
                id_data[key] = "id"
            else:
                id_data[key] = value
        elif key.startswith("@"):
            id_data[key] = value
        else:
            # Use manual translation if available
            if key in id_translations:
                id_data[key] = id_translations[key]
            else:
                # Keep Korean text as placeholder for missing translations
                id_data[key] = value
                print(f"Missing translation for: {key}")
    
    # Complete missing translations
    additional_translations = {
        "startWithEmail": "Mulai dengan Email",
        "startWithGoogle": "Mulai dengan Google",
        "loginError": "Error masuk",
        "loginCancelled": "Masuk dibatalkan",
        "basicInfo": "Informasi dasar",
        "emailHint": "contoh@email.com",
        "passwordHint": "Masukkan kata sandi",
        "nicknameHint": "Masukkan nama panggilan",
        "enterEmail": "Masukkan email",
        "profilePhoto": "Foto profil",
        "gender": "Jenis kelamin",
        "genderRequired": "Silakan pilih jenis kelamin",
        "birthDate": "Tanggal lahir",
        "birthDateRequired": "Silakan pilih tanggal lahir",
        "selectGender": "Pilih jenis kelamin",
        "genderOptional": "Jenis kelamin (opsional)",
        "birthDateOptional": "Tanggal lahir (opsional)",
        "setNow": "Atur sekarang",
        "myGenderSection": "Jenis kelamin saya",
        "personaGenderSection": "Jenis kelamin persona",
        "showAllGendersOption": "Tampilkan semua jenis kelamin",
        "accountAndProfile": "Akun & Profil",
        "enterBasicInformation": "Masukkan informasi dasar",
        "previous": "Sebelumnya",
        "completeSignup": "Selesaikan pendaftaran",
        "referrerEmailLabel": "Email perujuk",
        "year": "Tahun",
        "month": "Bulan",
        "day": "Hari",
        "selfIntroduction": "Perkenalan diri",
        "selfIntroductionHint": "Ceritakan tentang diri Anda",
        "usagePurpose": "Tujuan penggunaan",
        "selectFeeling": "Bagaimana perasaan Anda?",
        "anxious": "Cemas",
        "tired": "Lelah",
        "lonely": "Kesepian",
        "stressed": "Stres",
        "depressed": "Depresi",
        "calm": "Tenang",
        "allPersonas": "Semua persona",
        "chats": "Obrolan",
        "noChatsYet": "Belum ada obrolan",
        "todayChats": "Hari ini",
        "yesterdayChats": "Kemarin",
        "olderChats": "Lebih lama",
        "chatEndedMessage": "Obrolan berakhir",
        "messageDeleted": "Pesan dihapus",
        "unsendMessage": "Batalkan kirim pesan",
        "copyMessage": "Salin pesan",
        "messageCopied": "Pesan disalin",
        "voiceMessage": "Pesan suara",
        "signUp": "Daftar",
        "meetPersonas": "Temui persona",
        "allPersonasMatched": "Semua persona dicocokkan",
        "heartInsufficient": "Hati tidak cukup",
        "leaveChatTitle": "Tinggalkan obrolan",
        "leave": "Tinggalkan",
        "notSubscribed": "Tidak berlangganan",
        "purchaseConfirm": "Konfirmasi pembelian",
        "purchaseButton": "Beli",
        "discount20": "Diskon 20%",
        "discount30": "Diskon 30%",
        "hearts10": "10 Hati",
        "hearts30": "30 Hati",
        "hearts50": "50 Hati",
        "originalPrice": "Harga asli",
        "discountAmount": "Jumlah diskon",
        "hearts30Discount": "30 Hati (Diskon)",
        "hearts50Discount": "50 Hati (Diskon)",
        "editProfile": "Edit profil",
        "purchaseHeartsOnly": "Beli hati saja",
        "tutorialAccount": "Akun tutorial",
        "subscriptionStatus": "Status langganan",
        "editInfo": "Edit informasi",
        "joinDate": "Tanggal bergabung",
        "pushNotifications": "Notifikasi push",
        "soundSettings": "Pengaturan suara",
        "effectSound": "Efek suara",
        "themeSettings": "Pengaturan tema",
        "help": "Bantuan",
        "frequentlyAskedQuestions": "Pertanyaan yang sering diajukan",
        "searchFAQ": "Cari FAQ",
        "searchResults": "Hasil pencarian",
        "relatedFAQ": "FAQ terkait",
        "wasHelpful": "Apakah membantu?",
        "thanksFeedback": "Terima kasih atas masukan Anda",
        "others": "Lainnya",
        "accountManagement": "Manajemen akun",
        "howToUse": "Cara penggunaan",
        "inquiries": "Pertanyaan",
        "loginRequired": "Perlu masuk",
        "sonaFriend": "Teman SONA",
        "messagesRemaining": "{count} pesan tersisa",
        "matchedSuccess": "Cocok berhasil",
        "firstMatch": "Kecocokan pertama!",
        "dailyBonus": "Bonus harian",
        "welcomeGift": "Hadiah selamat datang",
        "tutorialComplete": "Tutorial selesai",
        "personalityTestComplete": "Tes kepribadian selesai",
        "profileComplete": "Profil lengkap",
        "firstChat": "Obrolan pertama",
        "tenChats": "10 obrolan",
        "hundredMessages": "100 pesan",
        "thousandMessages": "1000 pesan",
        "weeklyStreak": "Streak mingguan",
        "monthlyActive": "Aktif bulanan",
        "aiDatingQuestion": "Tertarik berkencan dengan AI?",
        "loginWithGoogle": "Masuk dengan Google",
        "loginWithApple": "Masuk dengan Apple",
        "googleLoginError": "Error masuk Google",
        "appleLoginError": "Error masuk Apple",
        "loginWithoutAccount": "Masuk tanpa akun",
        "logoutConfirm": "Yakin ingin keluar?",
        "intj": "INTJ",
        "intp": "INTP",
        "entj": "ENTJ",
        "entp": "ENTP",
        "infj": "INFJ",
        "infp": "INFP",
        "enfj": "ENFJ",
        "enfp": "ENFP",
        "istj": "ISTJ",
        "isfj": "ISFJ",
        "estj": "ESTJ",
        "esfj": "ESFJ",
        "istp": "ISTP",
        "isfp": "ISFP",
        "estp": "ESTP",
        "esfp": "ESFP",
        "music": "Musik",
        "movies": "Film",
        "books": "Buku",
        "sports": "Olahraga",
        "travel": "Perjalanan",
        "cooking": "Memasak",
        "gaming": "Gaming",
        "art": "Seni",
        "photography": "Fotografi",
        "fashion": "Mode",
        "technology": "Teknologi",
        "nature": "Alam",
        "animals": "Hewan",
        "fitness": "Kebugaran",
        "food": "Makanan",
        "coffee": "Kopi",
        "tea": "Teh",
        "wine": "Anggur",
        "beer": "Bir",
        "meditation": "Meditasi",
        "yoga": "Yoga",
        "dancing": "Menari",
        "singing": "Menyanyi",
        "writing": "Menulis",
        "blogging": "Blogging",
        "vlogging": "Vlogging",
        "podcasting": "Podcasting",
        "gardening": "Berkebun",
        "diy": "DIY",
        "crafts": "Kerajinan",
        "collecting": "Mengoleksi",
        "volunteering": "Sukarelawan",
        "languages": "Bahasa",
        "coding": "Coding",
        "investing": "Investasi",
        "entrepreneurship": "Kewirausahaan"
    }
    
    # Add additional translations to main data
    for key, value in additional_translations.items():
        if key in ko_data and key not in id_translations:
            id_data[key] = value
    
    # Handle remaining untranslated keys
    for key in ko_data.keys():
        if not key.startswith("@") and key not in id_data:
            id_data[key] = ko_data[key]  # Use Korean as fallback
    
    # Write Indonesian ARB file
    with open(id_arb_path, 'w', encoding='utf-8') as f:
        json.dump(id_data, f, ensure_ascii=False, indent=2)
    
    print(f"Indonesian ARB file created at: {id_arb_path}")
    
    # Count statistics
    total_keys = len([k for k in ko_data.keys() if not k.startswith("@")])
    translated_keys = len(id_translations) + len(additional_translations)
    
    print(f"\nStatistics:")
    print(f"Total keys: {total_keys}")
    print(f"Translated: {translated_keys}")
    print(f"Completion: {translated_keys/total_keys*100:.1f}%")
    
    return id_arb_path

if __name__ == "__main__":
    translate_to_indonesian()